on: [push, pull_request]

name: Cook recipes

jobs:
  cook:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} build

    env:
      CC: clang
      CXX: clang++
      OBJC: clang
      OBJCXX: clang++

    strategy:
      matrix:
        os: [ 'macOS-10.15' ]

    steps:
      - uses: actions/checkout@v2

      - name: Create Makefile
        run: Rscript scripts/mkmk.R

      - name: Remove local stuff
        run: |
          sudo mkdir /usr/local/.disabled
          sudo mv /usr/local/* /usr/local/.disabled/

      - name: Build tools
        run: |
          make -C build pkgconfig

      - name: Stubs
        run: |
          sudo mkdir -p /usr/local/lib/pkgconfig
          sudo cp stubs/pkgconfig-darwin/*.pc /usr/local/lib/pkgconfig/

      - name: Build R dependencies
        run: make -C build gmp mpfr

      - name: Verify gmp build
        env:
          GMP: build/gmp-6.2.1-dst/usr/local
        run: |
          echo "#include <gmp.h>" | ${CXX} -E -I${GMP}/include -xc++ - 2>&1
          if [ $? -ne 0 ]; then
            echo "failed"
            exit 1;
          fi

      - name: Verify gmpxx build
        env:
          GMP: build/gmp-6.2.1-dst/usr/local
        run: |
          echo "#include <gmpxx.h>" | ${CXX} -E -I${GMP}/include -xc++ - >/dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "failed"
            exit 1;
          fi

      - name: Verify package build
        run: |
          ls -la /usr/local/.disabled
          ls -la build/gmp-6.2.1-dst/usr/local
          ls -la build/gmp-6.2.1-dst/usr/local/include
          ls -la build/gmp-6.2.1-dst/usr/local/lib
          la -la build/mpfr-4.1.0-dst/usr/local
          la -la build/mpfr-4.1.0-dst/usr/local/include
          la -la build/mpfr-4.1.0-dst/usr/local/lib
          sudo mv /usr/local/.disabled/bin/R /usr/local/bin/R
          sudo cp -R build/gmp-6.2.1-dst/usr/local/include/* /usr/include
          sudo cp -R build/gmp-6.2.1-dst/usr/local/lib/* /usr/lib
          sudo cp -R build/mpfr-4.1.0-dst/usr/local/include/* /usr/include
          sudo cp -R build/mpfr-4.1.0-dst/usr/local/lib/* /usr/lib
          Rscript -e "install.packages('surveyvoi', repos='https://cloud.r-project.org/')"

      - name: Collect
        run: mkdir deploy && cp -p build/*-darwin*.tar.gz deploy/

      - name: Upload
        if: success()
        uses: actions/upload-artifact@master
        with:
          name: recipes-build
          path: deploy
