on: [push, pull_request]

name: Cook recipes

jobs:
  cook:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} build

    env:
      CC: clang
      CXX: clang++
      OBJC: clang
      OBJCXX: clang++

    strategy:
      matrix:
        os: [ 'macOS-10.15' ]

    steps:
      - uses: actions/checkout@v2

      - name: Create Makefile
        run: Rscript scripts/mkmk.R

      - name: Remove local stuff
        run: |
          sudo mkdir /usr/local/.disabled
          sudo mv /usr/local/* /usr/local/.disabled/

      - name: Build tools
        run: |
          make -C build pkgconfig

      - name: Stubs
        run: |
          sudo mkdir -p /usr/local/lib/pkgconfig
          sudo cp stubs/pkgconfig-darwin/*.pc /usr/local/lib/pkgconfig/

      - name: Build R dependencies
        run: make -C build gmp

      - name: Verify gmp build
        run: |
            echo "#include <gmp.h>" | ${CXX} -E -lgmp -xc++
            echo "#include <gmp.h>" | ${CXX} -E -lgmp -xc++ - >/dev/null 2>&1
            if [ $? -ne 0 ]; then
              echo "failed"
              exit 1;
            fi

        - name: Verify gmpxx build
        run: |
            echo "#include <gmpxx.h>" | ${CXX} -E -lgmpxx -xc++ - >/dev/null 2>&1
            if [ $? -ne 0 ]; then
              echo "failed"
              exit 1;
            fi

      - name: Collect
        run: mkdir deploy && cp -p build/*-darwin*.tar.gz deploy/

      - name: Upload
        if: success()
        uses: actions/upload-artifact@master
        with:
          name: recipes-build
          path: deploy
